
if(optimost.Q["opselect"]=="qa")optimost.SC("opselect","qa",null,optimost.SLD());var opIsStage=false;if(optimost.Q["opselect"]=="qa"||optimost.C["opselect"]=="qa"){opIsStage=true;}
window.optrial=window.optrial||{};optrial.opDeviceType="desktop";if(typeof(screen)!=="undefined"){if((screen.height>screen.width&&screen.height<=800&&screen.width<=480)||(screen.width>screen.height&&screen.width<=800&&screen.height<=480)){optrial.opDeviceType="mobile";}}
if(opIsStage){}
if(optimost.Q["opDevice"]){optrial.opDeviceType=optimost.Q["opDevice"];optimost.SC("opDevice",optimost.Q["opDevice"],null,optimost.SLD());}
var opDev=optimost.Q["opDevice"]||optimost.C["opDevice"]||"";if(opDev){optrial.opDeviceType=opDev;}
var opPro=(("https:"==document.location.protocol)?"https://by.essl.optimost.com/by":"http://by.optimost.com");var opDocLocation=document.location.toString();var opExperiments={};var opPageId=(typeof(opPageId)=="string"?opPageId:"");var opFireCtr=function(){var _o=(typeof opcounter=="object")?opcounter:new Object;_o.D=document;_o.L=_o.D.location;_o.T=new Date;_o.Q=new Object;_o.C=new Object;_o.U="https://by.essl.optimost.com/by/counter/112/-/54/event.js";_o.D_ts=Math.round(_o.T.getTime()/ 1000);_o.D_tzo=_o.T.getTimezoneOffset();_o.D_loc=_o.L.protocol+"//"+_o.L.hostname+_o.L.pathname;_o.D_ckl=_o.D.cookie.length;_o.D_ref=_o.D.referrer;function
_oI(){var s=_o.L.search;var c=_o.D.cookie;if(s.length>3){for(var a=s.substring(1).split("&"),i=0,l=a.length;i<l;i++){var p=a[i].indexOf("=");if(p>0)_o.Q[a[i].substring(0,p)]=unescape(a[i].substring(p+1));}}
if(c.length>3){for(var a=c.split(";"),i=0,b=a.length;i<b;i++){var v=a[i].split("=");while(v[0].substring(0,1)==" ")v[0]=v[0].substring(1,v[0].length);if(v.length==2)_o.C[v[0]]=unescape(v[1]);}}}
function _oS(){var o=new Object;for(var n in _o)o[n]=_o[n];o.D=o.L=o.T=o.Q=o.C=o.U=null;var q='';for(var n in o)
if(o[n]!=null&&o[n]!="")q+=(q.length>0?"&":(_o.U.indexOf("?")>0?"&":"?"))+n+"="+escape(o[n]);return _o.U+q;}
_oI();for(var n in _o.Q)
if(n.substring(0,2)=="op")_o[n]=_o.Q[n];for(var n in _o.C)
if(n.substring(0,2)=="op")_o[n]=_o.C[n];var h=document.getElementsByTagName("head")[0];if(h&&h.appendChild){window.s=document.createElement("script");s.type="text/javascript";s.src=_oS();h.appendChild(s);}}
for(var c in optimost.Q){if(c.indexOf("op")==0&&c.indexOf("opqa")==-1){optimost.SC(c,optimost.Q[c],86400,optimost.SLD());}}
optimost.I();optimost.findParam=function(p){var r="";for(var n in optimost.Q){if(n.toLowerCase()==p.toLowerCase()){r=optimost.Q[n].toLowerCase();}}
return r;}
window.optrial=window.optrial||{};var op_cid=optimost.findParam("cid");if(op_cid){optrial.op_cid=op_cid;}
var op_channel=optimost.findParam("channel");if(op_channel){optrial.op_channel=op_channel;}
opExperiments["tu govt search landing"]={"crumb":"TransUnion >> Search Landing Page (Government Breach)","method":"function","criteria":function(){var run=false;window.optrial=window.optrial||{};var ar_cidParams=['TU_NB_Credit_Card_Fraud_Exact','TU_NB_Credit_Card_Theft_Exact','TU_NB_Credit_Fraud_Exact','TU_NB_Credit_Theft_Exact','TU_NB_ID_Fraud_Exact','TU_NB_ID_Protection_Exact','TU_NB_ID_Theft_Exact','TU_NB_Identity_Fraud_Exact','TU_NB_Identity_Protection_Exact','TU_NB_Identity_Theft_Exact','TU_NB_Credit_Lock_Exact','TU_NB_Credit_Protection_Exact','TU_NB_Data_Breach_Exact','TU_NB_Fraud_Alert_Exact','TU_NB_Credit_Card_Fraud_Phrase','TU_NB_Credit_Card_Theft_Phrase','TU_NB_Credit_Fraud_Phrase','TU_NB_Credit_Theft_Phrase','TU_NB_ID_Fraud_Phrase','TU_NB_ID_Protection_Phrase','TU_NB_ID_Theft_Phrase','TU_NB_Identity_Fraud_Phrase','TU_NB_Identity_Protection_Phrase','TU_NB_Identity_Theft_Phrase','TU_NB_Credit_Lock_Phrase','TU_NB_Credit_Protection_Phrase','TU_NB_Data_Breach_Phrase','TU_NB_Fraud_Alert_Phrase','TU_NB_Credit_Card_Fraud_Phrase','TU_NB_ID_Protection_Exact','TU_NB_Credit_Card_Theft_Phrase','TU_NB_ID_Theft_Exact','TU_NB_Credit_Fraud_Phrase','TU_NB_Identity_Fraud_Exact','TU_NB_Credit_Theft_Phrase','TU_NB_Identity_Protection_Exact','TU_NB_ID_Fraud_Phrase','TU_NB_Identity_Theft_Exact','TU_NB_ID_Protection_Phrase','TU_NB_Credit_Card_Fraud_Exact','TU_NB_ID_Theft_Phrase','TU_NB_Credit_Card_Theft_Exact','TU_NB_Identity_Fraud_Phrase','TU_NB_Credit_Fraud_Exact','TU_NB_Credit_Theft_Exact','TU_NB_ID_Fraud_Exact','TU_NB_Identity_Protection_Phrase','TU_NB_Credit_Lock_Exact','TU_NB_Credit_Protection_Exact','TU_NB_Identity_Theft_Phrase','TU_NB_Data_Breach_Exact','TU_NB_Credit_Lock_Phrase','TU_NB_Fraud_Alert_Exact','TU_NB_Credit_Protection_Phrase','TU_NB_Data_Breach_Phrase','TU_NB_Fraud_Alert_Phrase','TU_B'];if((document.location.href.indexOf(".transunion.com/personal-credit/marketing/true-credit-optimost.page")!==-1||document.location.href.indexOf(".transunion.com/personal-credit/databreach.page")!==-1)&&optrial.op_cid){for(var z=0;z<ar_cidParams.length;++z){if(optrial.op_cid.toLowerCase().indexOf(ar_cidParams[z].toLowerCase())!==-1){run=true;break;}}}
return run;},"match":false,"unique":"/trial/112/p/searchlandingpagegovernmentbreac/213/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["tu_searchLanding"]};opExperiments["Orphan Pages - Branded Keywords T1"]={"crumb":"TransUnion >> Orphan Pages","method":"function","criteria":function(){var run=false;var path=document.location.pathname;window.optrial=window.optrial||{};if(document.location.hostname.indexOf("www.transunion.com")>-1||path=="/personal-credit/marketing/truecredit.page"){if(optrial.op_cid&&optrial.op_cid.indexOf('tu_b')>-1){run=true;}}
return run;},"match":false,"unique":"/trial/112/p/orphanpagebrandedkeywords/203/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"throttle":function(){var t=250;if(opIsStage){t=1000;}
return t;}(),"gum":function(){var g="op112orphanpagebrandedkeywordsgum ";if(opIsStage){g=null;}
return g;}(),"domain":function(){var d=optimost.SLD();if(opIsStage){d=null;}
return d;}(),"expire":function(){var e=2592000;if(opIsStage){e=null;}
return e;}(),"dwrite":true,"modules":["page"]};opExperiments["tu total"]={"crumb":"TransUnion >> TU Total","method":"var","entity":document.location.pathname,"criteria":"/personal-credit/marketing/tutotal.page","condition":"equals","match":false,"unique":"/trial/112/p/tutotal.465/134/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["Detail"]};opExperiments["tu vulcan 9.95"]={"crumb":"TransUnion >> TU.com Homepage [vulcan 9.95]","method":"var","entity":document.location.pathname,"criteria":"/personal-credit/marketing/3BM10054.page","condition":"equals","match":false,"unique":"/trial/112/p/tucomhomepage.763/108/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["Detail"]};opExperiments["tu mobile"]={"crumb":"TransUnion >> Mobbile Landing page","method":"var","entity":document.location.pathname,"criteria":"/personal-credit/TU_mobile_home.page","condition":"equals","match":false,"unique":"/trial/112/p/mobilelandingpage/149/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["Detail"]};opExperiments["tu orphan page"]={"crumb":"TransUnion >> TrueCredit - Orphan page","method":"function","criteria":function(){var run=false;var path=document.location.pathname;window.optrial=window.optrial||{};if(document.location.hostname.indexOf(".transunion.com")>-1&&path=="/personal-credit/marketing/truecredit.page"){if(document.location.search.toLowerCase().indexOf("ppc:adnet")>-1){run=true;}}
return run;},"match":false,"unique":"/trial/112/p/truecredit/179/content.js","dwrite":true,"modules":["tu_orphan_page"]};if(document.location.pathname.toLowerCase().indexOf("/personal-credit/credit-management.page")!=-1&&opDocLocation.indexOf("membership.tui")==-1){(function(){var _o=optimost;_o.U=opPro+"/trial/112/p/creditmanagement.16c/116/content.js";_o.ST="script";_o.SA={"type":"text/javascript"};_o.B();_o.R(1000,null,null,null);})();}
opExperiments["tucmp"]={"crumb":"TransUnion >> TUCMP","method":"var","entity":document.location.pathname,"criteria":"/personal-credit/marketing/tucmp.page","condition":"equals","match":false,"unique":"/trial/112/p/tucmp/155/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["Detail"]};opExperiments["tu affiliate"]={"crumb":"TransUnion >> TU Affiliate Page","method":"var","entity":document.location.pathname,"criteria":"/personal-credit/marketing/affiliate.page","condition":"equals","match":false,"unique":"/trial/112/p/tuaffiliatepage/158/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["Detail"]};opExperiments["TU Total Step 1 counter"]={"crumb":"TU Total Step 1","method":"function","entity":opDocLocation,"criteria":function(){var run=false;if(opDocLocation.indexOf(".transuniontotal.com/enroll")>-1){run=true;}
return run;},"condition":"contains","match":false,"unique":"/counter/112/-/53/event.js","throttle":1000,"gum":null,"domain":null,"expire":null,"modules":["counter"]};opExperiments["tu fbook"]={"crumb":"TransUnion >> Facebook Landing Page","method":"var","entity":document.location.pathname,"criteria":"/personal-credit/marketing/facebook.page","condition":"equals","match":false,"unique":"/trial/112/p/facebooklandingpage.42e/109/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["Detail"]};opExperiments["tu contest page"]={"crumb":"TransUnion >> Contest Page","method":"var","entity":document.location.pathname,"criteria":"/power-to-achieve","condition":"equals","match":false,"unique":"/trial/112/p/contestpage/165/content.js","throttle":1000,"gum":null,"domain":null,"expire":null,"dwrite":true,"modules":["contest"]};opExperiments["c member login"]={"crumb":"Counter: Member Login","method":"function","criteria":function(){var run=false;if(document.location.hostname.indexOf("membership.tui.transunion.com")>-1&&document.location.pathname=="/tucm/login.page"){run=true;}
return run;},"unique":"/counter/112/-/56/event.js","dwrite":true,"match":false,"modules":["nothinghere"]};optimost.identify=function(){for(var n in opExperiments){switch(opExperiments[n].method){case'function':if(typeof(opExperiments[n].criteria)=="function"&&opExperiments[n].criteria()){opExperiments[n].match=true;opExperiments[n].criteria=null;}
break;case'var':if(typeof(opExperiments[n].entity)!="undefined"){if(opExperiments[n].condition=="equals"){if(opExperiments[n].entity.toString()==opExperiments[n].criteria)opExperiments[n].match=true;}else if(opExperiments[n].condition=="contains"){if(opExperiments[n].entity.toString().indexOf(opExperiments[n].criteria)!=-1)opExperiments[n].match=true;}}
break;case'array':if(typeof(opExperiments[n].entity)=="object"){var len=opExperiments[n].entity.length;var len2=opExperiments[n].criteria.length;for(var i=0;i<len;i++){for(var j=0;j<len;j++){if(opExperiments[n].condition=="equals"){if(opExperiments[n].entity[i].toString()==opExperiments[n].criteria[j])opExperiments[n].match=true;}else if(opExperiments[n].condition=="contains"){if(opExperiments[n].entity[i].toString().indexOf(opExperiments[n].criteria[j])!=-1)opExperiments[n].match=true;}}}}
break;}}}
optimost.identify();optimost.createStyle=function(styleText){var head=document.getElementsByTagName('head')[0],style=document.createElement('style'),rules=document.createTextNode(styleText);style.type='text/css';if(style.styleSheet)
style.styleSheet.cssText=rules.nodeValue;else style.appendChild(rules);head.appendChild(style);}
optimost.TH=function(r,c,d,e){var b=true;if(r<1000){b=(Math.floor(Math.random()*1000)<r);if(c!=null){if(this.C[c]!=null)b=(this.C[c]!="mvt-no");else this.SC(c,b?"mvt-yes":"mvt-no",e,d);}
return b;}else return true;}
optimost.TX=function(){var t='<'+this.ST+' src="'+this.S()+'"';for(n in this.SA)t+=(" "+n+'="'+this.SA[n]+'"');t+='><\/'+this.ST+'>';this.D.write(t);}
optimost.isIE6=(navigator.userAgent.toLowerCase().indexOf("msie 6")!=-1?true:false);optimost.XH=function(u){if(typeof(u)!="object")return;var s=this.D.createElement(this.ST);for(var n in this.SA){if(!this.isIE6)s.setAttribute(n,this.SA[n]);else s[n]=this.SA[n];}
for(var n in u){if(!this.isIE6)s.setAttribute(n,u[n]);else s[n]=u[n];}
var h=this.D.getElementsByTagName("head");if(h[0])h[0].insertBefore(s,h[0].childNodes[h[0].childNodes.length-1]);else this.D.body.insertBefore(s,this.D.body.childNodes[D.body.childNodes.length-1]);}
optimost.RXH=function(r,c,d,e){if(this.Enabled){var b=true;if(r<1000){b=(Math.floor(Math.random()*1000)<r);if(c!=null){if(this.C[c]!=null)b=(this.C[c]!="mvt-no");else this.SC(c,b?"mvt-yes":"mvt-no",e,d);}}
if(b){var u={"src":this.S()};this.XH(u);}}}
var opModulesArray=[];var opContentUrls=["empty"];if(opDocLocation.indexOf(".transuniontotal.com/enroll")!=-1)opContentUrls.push("placeholder");(function(g,l,d,async,accountId){if(l.search.match(/[\?&]opDMH\=off/i)||d.cookie.match(/(^|;)\s*opDMH\=off/)){return false;}
var p="http://by.marketinghub.hp.com/es/"+accountId+"/c/0/u/customer.global.js",n,b,buster,dmhTest=l.search.match(/[\?&]dmhTest\=(.+)/i)||d.cookie.match(/(^|;)\s*dmhTest\=(.+)/);var esnocache=(!!dmhTest)||l.search.match(/[\?&]opnocache\=([^\?&#]+)/i)||d.cookie.match(/(^|;)\s*opnocache\=([^;]+)/);if(l.protocol==='https:'){p=p.replace(/^http\:\/\/by/,"https://secure");}
if(dmhTest){p=p.replace("customer.global.js","customer.global.test.js");}
if(esnocache){p=p.replace("/es/","/esnocache/");}
buster=l.search.match(/[\?&](dmhBuster\=\w+)/i)||d.cookie.match(/(^|;)\s*(dmhBuster\=\w+)/);if(buster){p=p+"?"+buster[1];}
g._dmhConfig={portfolioId:1,loadAsync:!!async,fullClickStream:true};n=d.createElement("script");n.src=p;if(async){b=d.getElementsByTagName("script")[0];b.parentNode.insertBefore(n,b);}else{d.write(n.outerHTML+"\n");}
return true;})(window,location,document,(document.readyState!=='loading'),1728);function openCounterDebugWindow(content){if(top.counterDebugWindow==null){top.counterDebugWindow=window.open("","counterDebugWindow","width=400,height=350,location=0,menubar=0,toolbar=0,status=0,scrollbars=1,resizable=1");top.counterDebugWindow.document.writeln("<html><head><title>Counters</title></head><body bgcolor=\"white\" onLoad=\"self.focus()\"><p>The following counter(s) were triggered from this page.</p>"+content+"</body></html>");top.counterDebugWindow.document.close();}else{top.counterDebugWindow.document.body.innerHTML+="<div>&nbsp;</div>"+content;}}
for(var n in opExperiments){if(opExperiments[n].match==true){for(var m in opExperiments[n]){if(typeof(opExperiments[n][m])=="function"&&opExperiments[n].throttle==1000)opExperiments[n][m]();}
if(opExperiments[n].unique.indexOf("event.js")!=-1){for(var j=0;j<opExperiments[n].modules.length;j++)opModulesArray.push(opExperiments[n].modules[j]);var _o=optimost;_o.U=opPro+opExperiments[n].unique;_o.ST="script";_o.SA={"type":"text/javascript"};_o.B();_o.RXH(opExperiments[n].throttle,opExperiments[n].gum,opExperiments[n].domain,opExperiments[n].expire);}else if(opExperiments[n].unique.indexOf("content.js")!=-1){for(var j=0;j<opExperiments[n].modules.length;j++)opModulesArray.push(opExperiments[n].modules[j]);(function(){var _o=optimost;_o.U=opPro+opExperiments[n].unique;_o.ST="script";_o.SA={"type":"text/javascript"};_o.B();if(opExperiments[n].throttle<1000){isIn=_o.TH(opExperiments[n].throttle,opExperiments[n].gum,opExperiments[n].domain,opExperiments[n].expire);if(isIn){for(var m in opExperiments[n]){if(typeof(opExperiments[n][m])=="function")opExperiments[n][m]();}
_o.TX();}}else if(opExperiments[n].dwrite){_o.R(opExperiments[n].throttle,opExperiments[n].gum,opExperiments[n].domain,opExperiments[n].expire);}else _o.RXH(opExperiments[n].throttle,opExperiments[n].gum,opExperiments[n].domain,opExperiments[n].expire);})();}else{for(var j=0;j<opExperiments[n].modules.length;j++)opModulesArray.push(opExperiments[n].modules[j]);}}}
if(opDocLocation.indexOf("transunion.com")!=-1&&(document.location.pathname=="/"||document.location.pathname=="")&&opDocLocation.indexOf("membership.tui")==-1){window.optrial=window.optrial||{};var oprun=true;if(optrial.op_cid&&optrial.op_cid.indexOf("ppc")>-1){oprun=false;}
if(optimost.C["op112emailorderformgum"]&&!opIsStage){oprun=false;}
if(oprun){(function(){var _o=optimost;_o.U=opPro+"/trial/112/p/tucomhomepage.763/108/content.js";var throt=200;if(opIsStage){throt=1000;}
_o.ST="script";_o.SA={"type":"text/javascript"};_o.B();_o.R(throt,"op112tucomhomepagegum",".transunion.com",2592000);})();opContentUrls.push(opPro+"/trial/112/p/tucomhomepage.763/108/content.js");opModulesArray.push("HP_exitofferlegalcopy");}}